version: '3.8'
services: 
  api:
    image: dockermike1809/umb-api
    environment:
      - PASSWORD=Hackathon
      - SMTP_SERVER=mail.gmx.ch
      - SMTP_PORT=587
      - SENDER_EMAIL=misconfiguration@gmx.ch
      - RECEIVER_EMAIL=simeon.schaer1@gmail.com
    networks:
      - backend

  frontend:
    image: dockermike1809/umb-frontend
    networks:
      - backend

  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      -  ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
      - frontend
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
volumes:
  caddy_data: